#!/bin/bash

APIKEY=""
FCOIN=""
TCOIN=""
AMT=""
USD=0
RATE=0

help_screen() {
        echo " " 
        echo "CCconvert v0.5.1 (Lothario)"
        echo " "
        echo "Usage: "
        echo " "
        echo "$0 -a <amount> -f <from_coin> -t <to_coin> [options]"
        echo " "
        echo "Options:  "
        echo "             -a|--amount     <amount>"
        echo "             -f|--from       <coin>"
	echo "             -t|--to         <coin>"
	echo "             -r|--rate	   BTC-COIN Rate to determine how much of -t COIN you will receive at -f COIN rate"
        echo "             -u|--usd,       Get USD price of converted coin also"
        echo "             -h|--help,      this help screen      "
        echo " "
        echo "Example: "
        echo "          $ ccconvert -a 30 -f ADA -t XMR"
        echo "          $ ccconvert -a 100 -f USD -t BTC"
        echo " "
	echo "          $ ccconvert -a 0.0002 -f btc -t xhv --rate 0.00011669"
	echo " " 
	echo "          0.0002 BTC ---> 2.428402 XHV"
 	echo " "
	echo "          0.0002 @ 0.00011669 BTC-XHV: 1.713970252119 XHV"
	echo " "
	echo "          $ ccconvert -a 2.36 -f XHV -t btc --rate 0.00011669"
 	echo " "
	echo "          2.36 XHV ---> .0001942752 BTC"
        echo " "
	echo "          2.36 @ 0.00011669 XHV-BTC: .000275388399 BTC "

        exit
        
}

convert_crypto() { 
        API="https://min-api.cryptocompare.com/data/price?fsym=${FCOIN}&tsyms=${TCOIN}&api_key=$APIKEY"
        RESULT=`curl -s "$API"`
        toAMT=`echo $RESULT | cut -d ":" -f 2 | sed -e 's/\}//g'`
        if [[ "$TCOIN" == "USD" ]]; then
               convAMT=`echo "scale=2; (($AMT*$toAMT)*100)/100" | bc`
        else 
               convAMT=`echo "scale=12; $AMT*$toAMT" | bc`
        fi
        echo " "
        if [[ $USD -eq 1 ]]; then
                APIUSD="https://min-api.cryptocompare.com/data/price?fsym=${TCOIN}&tsyms=USD&api_key=$APIKEY"
                USDRESULT=`curl -s "$APIUSD"`
                usdAMT=`echo $USDRESULT | cut -d ":" -f 2 | sed -e 's/\}//g'`
                USDconvAMT=`echo "scale=2; (($usdAMT*$convAMT)*100)/100" | bc`
                echo "$AMT $FCOIN ---> $convAMT $TCOIN ---> $USDconvAMT USD"
                echo " "                
        else
                echo "$AMT $FCOIN ---> $convAMT $TCOIN"
                echo " "        
        fi

	if (( $(echo  "$RATE  >  0" | bc -l) )); then
	        API="https://min-api.cryptocompare.com/data/price?fsym=${TCOIN}&tsyms=${FCOIN}&api_key=$APIKEY"
        	RESULT=`curl -s "$API"`
        	otoAMT=${toAMT}
	        toAMT=`echo $RESULT | cut -d ":" -f 2 | sed -e 's/\}//g'`
	        if (( $(echo "$toAMT > 1" | bc -l) )); then
			rateAMT=`echo "scale=12; ($RATE / $otoAMT)" | bc`
			TotalrateAMT=`echo "scale=12; ($convAMT*$rateAMT)" | bc`
			echo "$AMT @ $RATE $FCOIN-$TCOIN: $TotalrateAMT $TCOIN"
		else
			rateAMT=`echo "scale=12; ($toAMT / $RATE)" | bc`
			TotalrateAMT=`echo "scale=12; ($convAMT*$rateAMT)" | bc`
			echo "$AMT @ $RATE $FCOIN-$TCOIN: $TotalrateAMT $TCOIN"
		fi		
	fi

}


while [ "$#" -gt 0 ]; do
        key=${1}

        case ${key} in
                -f|--from)
                        FCOIN=${2^^}
                        shift
                        shift
                        ;;
		-t|--to)
                        TCOIN=${2^^}
                        shift
                        shift
                        ;;
                -a|--amount)
                        AMT=${2}
                        shift
                        shift
                        ;;
                -u|--usd)
                        USD=1
                        shift
                        ;;
		-r|--rate)
			RATE=${2}
			shift
			shift
			;;
                -h|--help)
                        help_screen
                        shift
                        ;;
                				
                *)
                        shift
                        ;;
        esac
done

if [[ -z $FCOIN ]] || [[ -z $TCOIN ]] || [[ -z $AMT ]]; then
        help_screen

else
        convert_crypto
fi








